# Generated by Django 3.2.18 on 2023-04-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_streaming_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='streaming_service',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Prime', 'Prime'), ('Apple TV', 'Apple TV')], default='Netflix', max_length=10),
        ),
    ]
